### ISSUE TITLE
Person: Unnecessary function

### ISSUE THREAD

**Issue by jzych** [OriaTori/CS_Database#11]
Function serve no purpose and can be removed. Person can remain pure abstract function and class Student doesn't have its own implementation of it.

https://github.com/OriaTori/CS_Database/blob/483302198cbc63f8a8550a2fb4cff16d29839f91/src/Person.cpp#L57-L60

**Comment by LordLukin** [comment]
It's used for null object pattern to avoid dynamic_casts :)

**Comment by jzych** [comment]
Ok, then I'll close this issue.
